Feature/us13 tc03 buy tickets
ismailkoembe/EasyBusTicketTeam1 pull request #57
Opened 2024-01-12 19:59 UTC by GulnurTaskin

2024-01-12 20:01 UTC, GulnurTaskin commented
thank you

2024-01-14 07:44 UTC, aslierk commented
Binary dosyalar var Gülnurcum

2024-01-14 19:35 UTC, OVALIAYCA requested changes
merge edilmeyecek

2024-01-16 20:14 UTC, closed without merging

2024-01-16 20:14 UTC, GulnurTaskin commented
the end