Admin sidebar Booking History
ismailkoembe/EasyBusTicketTeam1 pull request #68
Opened 2024-01-13 20:55 UTC by reyhany

2024-01-13 21:22 UTC, aslierk requested changes

2024-01-13 21:22 UTC, aslierk commented on src/test/java/com/easybusticket/pages/AdminDashboardPage.java
> +    public void bookingHistoryDropdown(){
softassert yapiyoruzReyhan hocam.

2024-01-13 23:17 UTC, aslierk approved these changes

2024-01-13 23:54 UTC, OVALIAYCA approved these changes

2024-01-14 08:12 UTC, nazimekirkgoz reviewed
![image](https://github.com/ismailkoembe/EasyBusTicketTeam1/assets/121150630/00e189a5-dc11-4777-be04-360fb227b11a)
 bunlar aynimi ..

2024-01-14 08:13 UTC, nazimekirkgoz reviewed
conflict var

2024-01-14 09:24 UTC, GulnurTaskin commented
bosluklar silindi

2024-01-14 09:25 UTC, merged