Feature/home page locate header
ismailkoembe/EasyBusTicketTeam1 pull request #8
Opened 2024-01-09 20:52 UTC by sevvaltufekci

Merhaba, 
HomePage - header locatelerini ekledim, kontrolünüzü rica ederim.

2024-01-09 21:43 UTC, aslierk commented
![Screenshot 2024-01-09 224025](https://github.com/ismailkoembe/EasyBusTicketTeam1/assets/142500631/b4300193-99d3-4797-8e38-7ea5c6a527b8)

Merhaba Sevval. Reviwer olarak Ismail Hocayi ve bir arkadasi eklemen gerekiyor. Assignment kismina da kendi ismini yazman lazim.  Bir de bazi conflictler var. 17-21 arasinda bir conflict görünüyor. bos sanirim. Tesekkürler, iyi calismalar

2024-01-09 21:54 UTC, sevvaltufekci commented
Merhaba Aslı, reviewers düzenlemesini sağladım. Conflit kısmında daha önce eklenen cookie buton locate'i var. Hatalı bir işlem yapmamak adına silmek istemedim, alt kısımda yer alan metodu etkiliyor. Nasıl bir yol izleyebiliriz?

2024-01-09 22:04 UTC, aslierk reviewed
Su anda cözülmüs görünüyor. 18 haricindekileri silip birlestirdigini görüyorum. Ellerine sagllik:) Sadece yeni farkettigim birsey var. 78 sonrasindaki buyuk bosluk saniirm diger body ve footer icin bos birakilmis. ellerine saglik:)

2024-01-09 22:07 UTC, aslierk approved these changes

2024-01-10 09:45 UTC, OVALIAYCA approved these changes

2024-01-10 09:57 UTC, aslierk requested changes
Bazi cakismalar var. bunlara bakmaliyiz

2024-01-10 09:59 UTC, OVALIAYCA requested changes
conflig var

2024-01-10 10:42 UTC, sevvaltufekci commented
Aslı selam, conflig giderildi, kontrollerinizi rica ederim.

2024-01-10 11:19 UTC, ismailkoembe commented
Sevval hanim bana hatirlatirsaniz sonra size bu duruma dusmemek icin neler yapabiliriz anlatabilirim. Ama hatirlatmazsaniz unuturum 😄

2024-01-10 11:55 UTC, sevvaltufekci commented
Son düzeltmeler için kontrolünüzü rica ederim.

2024-01-10 12:03 UTC, OVALIAYCA approved these changes
header locate için teşekkürler

2024-01-10 12:04 UTC, aslierk approved these changes

2024-01-10 12:05 UTC, merged